'use client';
import {useState} from 'react';
import {zhCN} from 'date-fns/locale';
import {Calendar} from '@/components/ui/calendar';
import {diaryDayKind} from '@/lib/prompts';
import {dayKey,parseDay} from '@/lib/diary-dates';
import type {RecordItem} from '@/lib/store';
import {ArrowLeft,BookOpen,ChevronRight} from 'lucide-react';
export function DiaryCalendar({records,selected,onSelect,onBack,disabled}:{records:RecordItem[];selected:string;onSelect:(date:string)=>Promise<void>;onBack:()=>void;disabled:boolean}){
 const [month,setMonth]=useState(parseDay(selected)||new Date());const counts=new Map<string,number>();records.filter(r=>r.kind==='message').forEach(r=>counts.set(r.date,(counts.get(r.date)||0)+1));const moodOnly=(d:string)=>diaryDayKind(records.filter(r=>r.kind==='message'&&r.date===d))==='mood';const prefix=dayKey(month).slice(0,7);const dates=[...counts.keys()].filter(d=>d.startsWith(prefix)).sort().reverse();
 return <div className="content-page diary-calendar-page"><div className="detail-header"><button className="outline" onClick={onBack}><ArrowLeft size={18}/>返回日记</button><button className="outline" disabled={disabled} onClick={()=>onSelect(dayKey(new Date()))}>回到今天</button></div><header className="page-head"><div><h1>日记日历</h1><p>点选任意过去的日期，查看或补写那一天。</p></div></header><div className="calendar-layout"><section className="calendar-panel"><Calendar className="diary-calendar" mode="single" required locale={zhCN} weekStartsOn={1} captionLayout="dropdown" startMonth={new Date(1970,0)} endMonth={new Date()} month={month} onMonthChange={setMonth} selected={parseDay(selected)||undefined} disabled={disabled?true:{after:new Date()}} onSelect={value=>{if(value)void onSelect(dayKey(value))}} modifiers={{recorded:[...counts.keys()].flatMap(d=>!moodOnly(d)&&parseDay(d)?[parseDay(d)!]:[]),moodOnly:[...counts.keys()].flatMap(d=>moodOnly(d)&&parseDay(d)?[parseDay(d)!]:[])}} modifiersClassNames={{recorded:'has-diary',moodOnly:'has-mood'}} labels={{labelDayButton:date=>`${date.toLocaleDateString('zh-CN')}，${counts.get(dayKey(date))?`${counts.get(dayKey(date))} 条记录${moodOnly(dayKey(date))?'，只有心情':''}`:'无记录，可补写'}`}}/><p className="calendar-legend"><span>● 日记　○ 只有心情</span> · 空白日期也可以补录</p></section><section><h2>{month.getFullYear()} 年 {month.getMonth()+1} 月 · {dates.length} 篇日记</h2>{dates.length?dates.map(d=><button className="list-row calendar-entry" key={d} disabled={disabled} onClick={()=>onSelect(d)}><BookOpen size={20}/><span><strong>{parseDay(d)!.toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'short'})}</strong><small>{counts.get(d)} 条记录</small></span><ChevronRight size={18}/></button>):<div className="practice-empty">这个月还没有日记。<br/>点击日期，就能留下一点那天的事。</div>}</section></div></div>
}
