'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Mic,Shuffle,ArrowUp,Plus,History,Sun,ArrowLeft,Pencil,ShieldCheck,X,Check,Heart,MessageCircle} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Recorder,Media,fmt} from './recorder';
import {PROMPTS,nextPrompt,MOODS,type Prompt} from '@/lib/prompts';
import {track} from '@/lib/analytics';
import {dayKey} from '@/lib/diary-dates';
import {preparePhoto} from '@/lib/images';
import {uid,type RecordItem} from '@/lib/store';
const dateLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric'});
const timeLabel=(at:number)=>new Date(at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});
let introSeenInSession=false;
const INTRO_KEY='sayit-prompt-intro-seen';
function consumeIntro(){introSeenInSession=true;try{localStorage.setItem(INTRO_KEY,'1')}catch{}}
function hasSeenIntro(){try{return introSeenInSession||localStorage.getItem(INTRO_KEY)==='1'}catch{return introSeenInSession}}
let visitPrompt=nextPrompt([]);let visitUsed=[visitPrompt.id];
type Props={records:RecordItem[];date:string;draft:string;onDraftChange:(text:string)=>void;commit:(records:RecordItem[],removed?:string[])=>Promise<void>;onBusy:(value:boolean)=>void;onCalendar:()=>void;onToday:()=>void;menu:(record:RecordItem)=>ReactNode};
export function DiaryV2({records,date,draft,onDraftChange,commit,onBusy,onCalendar,onToday,menu}:Props){
 const [prompt,setPrompt]=useState<Prompt>(visitPrompt),[activePrompt,setActivePrompt]=useState<Prompt|null>(null),[sheet,setSheet]=useState<'prompt'|'mood'|'done'|'denied'|null>(null),[mood,setMood]=useState(''),[voice,setVoice]=useState(false),[startRequest,setStartRequest]=useState(0),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[hint,setHint]=useState(false),[photos,setPhotos]=useState<RecordItem[]>([]);
 const used=useRef<string[]>(visitUsed),interacted=useRef(!!draft),nudged=useRef(false),photoInput=useRef<HTMLInputElement>(null),textInput=useRef<HTMLTextAreaElement>(null),card=useRef<HTMLElement>(null),composer=useRef<HTMLDivElement>(null),saveLock=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const today=dayKey(new Date()),historical=date!==today,all=records.filter(r=>r.kind==='message'),messages=all.filter(r=>r.date===date).sort((a,b)=>a.created-b.created),returning=all.length>0,disabled=busy||saving;
 const propsFor=(p:Prompt|null=activePrompt)=>({entry_type:p?'prompt':'free',...(p?{prompt_id:p.id,prompt_category:p.category}:{})});
 function touch(){interacted.current=true;setHint(false)}
 function notify(text:string){setNotice(text);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setNotice(''),4500)}
 useEffect(()=>{onBusy(busy||saving||photos.length>0)},[busy,saving,photos.length]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 useEffect(()=>{if(draft.trim())interacted.current=true},[draft]);
 useEffect(()=>{track('home_viewed');if(historical||hasSeenIntro())return;const onHidden=()=>{if(document.hidden)interacted.current=true};document.addEventListener('visibilitychange',onHidden);const timeout=setTimeout(()=>{if(!interacted.current&&!nudged.current&&!document.hidden&&!hasSeenIntro()){nudged.current=true;consumeIntro();setSheet('prompt')}},9000);return()=>{clearTimeout(timeout);document.removeEventListener('visibilitychange',onHidden)}},[]);
 useEffect(()=>{if(!card.current||historical)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){track('daily_prompt_viewed',{prompt_id:prompt.id,prompt_category:prompt.category});observer.disconnect()}},{threshold:0.5});observer.observe(card.current);return()=>observer.disconnect()},[prompt.id,historical]);
 function changePrompt(){touch();const next=nextPrompt(used.current);used.current=used.current.length>=PROMPTS.length?[next.id]:[...used.current,next.id];visitPrompt=next;visitUsed=used.current;setPrompt(next);track('prompt_changed',{prompt_id:next.id,prompt_category:next.category})}
 function record(p:Prompt|null){if(disabled)return;touch();setError('');setActivePrompt(p);setSheet(null);setVoice(true);setStartRequest(v=>v+1);track(p?'prompt_record_clicked':'free_record_clicked',propsFor(p));setTimeout(()=>composer.current?.scrollIntoView({behavior:'smooth',block:'center'}),80)}
 function openMood(){touch();setMood('');setError('');setSheet('mood');track('mood_entry_clicked',{entry_type:'mood'})}
 async function saveMood(){if(!mood||saveLock.current)return;saveLock.current=true;setSaving(true);onBusy(true);setError('');const at=Date.now();try{await commit([{id:uid(),kind:'message',type:'mood',mood,date,created:at,updated:at}]);track('mood_saved',{entry_type:'mood',mood_type:mood});setSheet('done')}catch(e:any){setError(e.message||'这份心情还没收好，请再试一次。')}finally{setSaving(false);saveLock.current=false;onBusy(false)}}
 async function sendText(){if(!draft.trim()||saveLock.current)return;touch();saveLock.current=true;setSaving(true);onBusy(true);setError('');const at=Date.now(),text=draft;try{await commit([{id:uid(),kind:'message',type:'text',date,text,created:at,updated:at,prompt:activePrompt?.text,promptId:activePrompt?.id,promptCategory:activePrompt?.category}],['diary-draft:'+date]);onDraftChange('');setActivePrompt(null);track('text_saved',{...propsFor(),entry_type:'text'});notify('这几句话，已经留下来了。')}catch(e:any){setError(e.message||'还没保存好，文字仍然留在这里。')}finally{saveLock.current=false;setSaving(false);onBusy(false)}}
 async function addAudio(blob:Blob,seconds:number,started:number,interrupted:boolean){try{await commit([{id:uid(),kind:'message',type:'audio',date,blob,seconds,started,created:started,updated:Date.now(),interrupted,prompt:activePrompt?.text,promptId:activePrompt?.id,promptCategory:activePrompt?.category}]);track('record_completed',{...propsFor(),record_duration:seconds});setActivePrompt(null);notify(`刚刚的 ${fmt(seconds)}，已经留下来了。`)}catch(e){track('record_save_failed',propsFor());throw e}}
 async function choosePhotos(files:FileList|null){if(!files?.length||disabled)return;touch();setSaving(true);onBusy(true);setError('');try{const add:RecordItem[]=[];for(const file of Array.from(files).slice(0,3-photos.length))add.push({id:uid(),kind:'message',type:'image',blob:await preparePhoto(file),updated:Date.now()});setPhotos(old=>[...old,...add])}catch(e:any){setError(e.message||'图片还没有准备好，请重试。')}finally{setSaving(false);onBusy(false)}}
 async function sendPhotos(){if(saveLock.current||!photos.length)return;saveLock.current=true;setSaving(true);onBusy(true);try{await commit(photos.map((p,i)=>({...p,date,created:Date.now()+i,updated:Date.now()})));setPhotos([]);track('image_saved',{entry_type:'image'});notify('这些画面，已经留下来了。')}catch(e:any){setError(e.message||'图片仍未保存，请重试。')}finally{saveLock.current=false;setSaving(false);onBusy(false)}}
 function calendar(){touch();if(photos.length){setError('还有待发送的图片，请先发送或移除。');return}onCalendar()}
 const selectedMood=MOODS.find(m=>m.id===mood);
 return <div className="diary-page diary-v2" onPointerDownCapture={touch} onKeyDownCapture={touch}>
 <header className="page-head"><div><p className="eyebrow">{new Date(date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}</p><h1>和自己聊聊 <Sun size={27}/></h1><p>{historical?`留一点 ${dateLabel(date)} 的自己。`:returning?'又见面了。今天，有什么想留给自己？':'今天，有什么想留给自己？'}</p></div><button className="outline" disabled={disabled} onClick={calendar}><History size={17}/>日记日历</button></header>
 <div className="v2-entry-actions"><button className="primary" disabled={disabled} onClick={()=>record(null)}><Mic size={19}/>我想说说</button><button className="quiet-entry" disabled={disabled} onClick={openMood}>今天不想说话 <Heart size={15}/></button></div>
 {!historical&&<section className="daily-question" ref={card}><div className="question-top"><span><span className="tiny-orbit"/>今天的问题</span><small>一个小问题，一点点自己</small></div><h2 key={prompt.id} className="question-text">{prompt.text}</h2><div className="question-actions"><button className="question-answer" disabled={disabled} onClick={()=>record(prompt)}><Mic size={17}/>{returning?'回答这个问题':'说说看'}<span>↗</span></button><button className="subtle" disabled={disabled} onClick={changePrompt}><Shuffle size={15}/>换一个</button></div></section>}
 <div className="v2-gentle-row"><span>不必说得完整，想到哪里就到哪里。</span><button className={'subtle help-entry '+(hint?'hint-once':'')} disabled={disabled} onClick={()=>{touch();consumeIntro();setSheet('prompt')}}>不知道说什么？</button></div>
 <section className="conversation"><div className="date-line"><span>{dateLabel(date)}{historical?'':' · 今天'}{messages.length?` · ${messages.length} 个片刻`:''}</span>{historical&&<button className="subtle" disabled={disabled||!!photos.length} onClick={onToday}>回到今天</button>}</div>
 {messages.length>0?<div className="messages">{messages.map(m=><div className="message-wrap" key={m.id}>{m.prompt&&<div className="prompt-snapshot"><span>今天的问题</span><p>{m.prompt}</p></div>}<div className={'message '+(m.type==='mood'?'mood-message':'')}>{m.type==='mood'?<><span className="mood-symbol">{MOODS.find(x=>x.id===m.mood)?.emoji||'😶'}</span><p>今天没有说什么。<br/><strong>但你来过这里。</strong></p></>:m.type==='text'?<p>{m.text}</p>:<Media record={m}/>}<div className="message-footer"><span>{timeLabel(m.created)}{m.interrupted?' · 中断片段':''}</span>{menu(m)}</div></div></div>)}</div>:<p className="v2-empty-note"><MessageCircle size={18}/>一句话、一段声音，或只是一个心情，都可以。</p>}
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="v2-saved" role="status"><Check size={16}/>{notice}</p>}
 {activePrompt&&<div className="pending-prompt"><div><small>正在回答</small><p>{activePrompt.text}</p></div><button className="icon-button" aria-label="移除问题" disabled={disabled} onClick={()=>setActivePrompt(null)}><X size={16}/></button></div>}
 {photos.length>0&&<div className="picture-previews">{photos.map(p=><div key={p.id}><Media record={p}/><button className="icon-button" disabled={disabled} aria-label="移除待发送图片" onClick={()=>setPhotos(old=>old.filter(x=>x.id!==p.id))}><X size={15}/></button></div>)}<button className="primary" disabled={disabled} onClick={sendPhotos}>发送图片（{photos.length}）</button></div>}
 <div className="composer" ref={composer}>{voice?<Recorder limit={60} label="开始录音" note="每段最长 60 秒 · 只保存在此浏览器" explainPermission startRequest={startRequest} onSave={addAudio} onBusy={value=>{setBusy(value);onBusy(value)}} onStarted={()=>track('record_started',propsFor())} onDenied={()=>{track('microphone_denied',propsFor());setSheet('denied')}} onCancelled={()=>track('record_cancelled',propsFor())}/>:<textarea ref={textInput} value={draft} readOnly={saving} onChange={e=>{touch();onDraftChange(e.target.value)}} placeholder="也可以写几句话，留给自己……" aria-label="日记内容" onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();void sendText()}}}/>}
 <div className="composer-bottom"><div><button className="icon-button" disabled={disabled||photos.length>=3} aria-label="添加图片" onClick={()=>photoInput.current?.click()}><Plus size={21}/></button><button className="voice-button" disabled={disabled} onClick={()=>voice?setVoice(false):record(null)}>{voice?<Pencil size={16}/>:<Mic size={16}/>} {voice?'写几句话':'说一小段'}</button></div>{!voice&&<button className="send" disabled={!draft.trim()||disabled} aria-label="发送日记" onClick={sendText}><ArrowUp size={20}/></button>}</div></div><p className="save-note"><ShieldCheck size={14}/>只在此设备保存，不必期待回应。</p>
 </section><input ref={photoInput} hidden type="file" accept="image/*" multiple onChange={e=>{void choosePhotos(e.target.files);e.target.value=''}}/>
 <Sheet open={sheet!==null} onOpenChange={open=>{if(!open&&!saving)setSheet(null)}}><SheetContent side="bottom" className="v2-sheet" showCloseButton={!saving}><span className="sheet-handle"/>
 {sheet==='prompt'&&<><SheetTitle>不知道从哪里开始？</SheetTitle><SheetDescription>那就回答一个小问题。说一句，也可以。</SheetDescription><p key={prompt.id} className="sheet-question question-text">{prompt.text}</p><button className="primary" onClick={()=>record(prompt)}><Mic size={18}/>说说看</button><button className="subtle" onClick={changePrompt}><Shuffle size={16}/>换一个问题</button></>}
 {sheet==='mood'&&<><SheetTitle>那就留一个今天的心情吧。</SheetTitle><SheetDescription>不用说什么也可以。{historical?`这份心情将留在 ${dateLabel(date)}。`:''}</SheetDescription><div className="mood-options" role="group" aria-label="选择心情">{MOODS.map(m=><button key={m.id} disabled={saving} aria-pressed={mood===m.id} aria-label={m.label} onClick={()=>{setMood(m.id);track('mood_selected',{entry_type:'mood',mood_type:m.id})}}><span>{m.emoji}</span><small>{m.label}</small></button>)}</div><p className="mood-caption">{selectedMood?selectedMood.label:'选一个此刻更接近你的表情。'}</p>{error&&<p className="error" role="alert">{error}</p>}{mood&&<button className="primary" disabled={saving} onClick={saveMood}>{saving?'正在收好这份心情…':'留下今天'}</button>}</>}
 {sheet==='done'&&<><span className="mood-done">{selectedMood?.emoji}</span><SheetTitle>今天也留下来了。</SheetTitle><SheetDescription>{dateLabel(date)} · {selectedMood?.label}</SheetDescription><button className="primary" onClick={()=>setSheet(null)}>完成</button></>}
 {sheet==='denied'&&<><SheetTitle>没有关系。</SheetTitle><SheetDescription>暂时无法使用麦克风。你仍然可以写下来，或者只留一个今天的心情。</SheetDescription><button className="primary" onClick={()=>{setSheet(null);setVoice(false);setTimeout(()=>textInput.current?.focus(),100)}}><Pencil size={17}/>写下来</button><button className="outline" onClick={openMood}><Heart size={17}/>留个心情</button></>}
 </SheetContent></Sheet>
 </div>
}
