'use client';
import {useState} from 'react';
import {ArrowLeft,Check,Mic,Timer,ShieldCheck} from 'lucide-react';
import {Recorder,Media} from './recorder';
import type {RecordItem} from '@/lib/store';
export function Interview({topic,items,onSave,onBusy,onBack}:{topic:RecordItem;items:RecordItem[];onSave:(item:RecordItem,blob:Blob,seconds:number,start:number,interrupted:boolean)=>Promise<void>;onBusy:(value:boolean)=>void;onBack:()=>void}){
 const [questions]=useState(()=>items.map(item=>({...item}))),[started,setStarted]=useState(false),[index,setIndex]=useState(0),[finished,setFinished]=useState(false),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[sessionAudio,setSessionAudio]=useState<RecordItem[]>([]);
 const question=questions[index];const setRecordingBusy=(value:boolean)=>{setBusy(value);onBusy(value)};
 return <div className="content-page interview-page"><div className="detail-header"><button className="outline" disabled={busy} onClick={onBack}><ArrowLeft size={18}/>返回主题</button><span><ShieldCheck size={16}/>固定流程 · 无 AI 调用</span></div><header className="page-head"><div><p className="eyebrow">MOCK INTERVIEW</p><h1>{finished?'本轮面试已结束':'限时模拟面试'}</h1><p>{topic.name}</p></div></header>{!started?<section className="interview-brief"><Timer size={32}/><h2>给自己一次不看稿的表达机会</h2><ul><li>使用这个主题中的 {questions.length} 个问题，按顺序逐题作答。</li><li>每题最长 2 分钟，到时自动结束并保存；可以提前交卷。</li><li>过程中隐藏准备稿，不提供暂停、跳题或本轮重答。</li><li>每题成功保存后才能进入下一题。新录音会替换该事项原有录音。</li></ul><p className="muted">这是本地固定流程模拟，不会根据回答追问或评分。已有录音在新录音保存成功前始终保留。</p><button className="primary" disabled={!questions.length} onClick={()=>setStarted(true)}><Mic size={18}/>进入面试</button></section>:finished?<section className="interview-review"><h2><Check size={22}/>已保存 {sessionAudio.length} 个回答</h2><p className="muted">逐题回听：有没有先说结论？例子够具体吗？有没有遗漏关键事实？</p>{sessionAudio.map(r=><article key={r.id} className="audio-card"><h2>{r.name}</h2>{r.interrupted&&<small>中断片段</small>}<Media record={r}/></article>)}<button className="outline" onClick={onBack}>回到主题整理准备稿</button></section>:<section className="interview-question"><div className="interview-progress"><span>问题 {index+1} / {questions.length}</span><span><Timer size={16}/>回答上限 02:00</span></div><h2>{question.name}</h2><p className="muted">准备稿已隐藏。点击开始后计时，保存后进入下一题。</p>{saved?<div className="stack-actions"><p className="saved-answer"><Check size={18}/>本题回答已保存</p><button className="primary" onClick={()=>{if(index+1===questions.length)setFinished(true);else{setIndex(index+1);setSaved(false)}}}>{index+1===questions.length?'结束并回听':'进入下一题'}</button></div>:<Recorder key={question.id} limit={120} label="开始回答" note="最长 2 分钟 · 到时自动保存 · 本轮不重答" onBusy={setRecordingBusy} onSave={async(blob,seconds,start,interrupted)=>{await onSave(question,blob,seconds,start,interrupted);setSessionAudio(prev=>[...prev,{...question,blob,type:'audio',seconds,started:start,interrupted}]);setSaved(true)}}/>}<small className="muted">离开面试后，已保存的回答仍在各自事项中；未作答题目不会新增录音。</small></section>}</div>
}
