'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Quote,AudioLines,FolderHeart,ArrowUpRight,History,ChevronDown,Plus,Mic,ArrowUp,ShieldCheck,Sun,Sparkles,Heart,Leaf,ArrowLeft,Trash2,Pencil,Download,Upload,HardDrive,X,Check,ChevronRight,Eye,EyeOff,MoreHorizontal} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {allRecords,writeRecords,wipe,uid,encodeBackup,decodeBackup,type RecordItem} from '@/lib/store';
import {Recorder,Media,fmt} from './recorder';
import {ScriptEditor} from './script-editor';
import {preparePhoto} from '@/lib/images';
import {DiaryCalendar} from './diary-calendar';
import {DiaryV2} from './diary-v2';
import {Interview} from './interview';
import {dayKey,validDiaryDay} from '@/lib/diary-dates';
const NAV=[{id:'diary',title:'日记',sub:'今天，和自己聊聊',Icon:BookOpen},{id:'quotes',title:'拾句',sub:'留下喜欢的表达',Icon:Quote},{id:'prep',title:'准备',sub:'给重要的话一点准备',Icon:FolderHeart},{id:'me',title:'我的',sub:'妥善收好每一份记录',Icon:ShieldCheck}];
const today=()=>dayKey(new Date());
const dateLabel=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric'});
const timeLabel=(t:number)=>new Date(t).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
export default function Home(){
const [processingPhotos,setProcessingPhotos]=useState(false);
const [records,setRecords]=useState<RecordItem[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[view,setView]=useState('diary'),[selected,setSelected]=useState(''),[date,setDate]=useState(today),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[modal,setModal]=useState<any>(null),[confirm,setConfirm]=useState<any>(null),[form,setForm]=useState<any>({}),[filter,setFilter]=useState('全部'),[promptText,setPromptText]=useState(''),[voice,setVoice]=useState(false),[draft,setDraft]=useState(''),[editor,setEditor]=useState<any>(null),[hideText,setHideText]=useState(false),[mode,setMode]=useState('看原文练习'),[pictures,setPictures]=useState<RecordItem[]>([]),[estimate,setEstimate]=useState<any>(null),[incoming,setIncoming]=useState<RecordItem[]|null>(null),[replace,setReplace]=useState(false);
const dateRef=useRef(today()),switchingDate=useRef(false);
const scriptFlush=useRef<(()=>Promise<void>)|null>(null);
const recordRef=useRef(records),busyRef=useRef(false),modalRef=useRef(modal),editorRef=useRef(editor),draftTimer=useRef<any>(null),editorTimer=useRef<any>(null),draftRef=useRef(draft),channel=useRef<BroadcastChannel|null>(null),photoInput=useRef<HTMLInputElement>(null),importInput=useRef<HTMLInputElement>(null);dateRef.current=date;recordRef.current=records;busyRef.current=busy;modalRef.current=modal;editorRef.current=editor;draftRef.current=draft;
const current=records.find(r=>r.id===selected),messages=records.filter(r=>r.kind==='message'&&r.date===date).sort((a,b)=>a.created-b.created),excerpts=records.filter(r=>r.kind==='excerpt').sort((a,b)=>b.updated-a.updated),topics=records.filter(r=>r.kind==='topic').sort((a,b)=>b.updated-a.updated),interests=records.filter(r=>r.kind==='interest'),practices=records.filter(r=>r.kind==='practice'&&r.parent===selected).sort((a,b)=>b.started-a.started);
async function reload(){try{setRecords(await allRecords());setReady(true)}catch{setError('无法读取此浏览器的内容。请检查存储权限后重试。')}}
function flash(text:string){setNotice(text);setTimeout(()=>setNotice(''),4000)}
async function commit(add:RecordItem[],del:string[]=[],expected?:RecordItem[]){await writeRecords(add,del,expected);setRecords(previous=>{const changed=new Set([...del,...add.map(r=>r.id)]);return [...previous.filter(r=>!changed.has(r.id)),...add]});try{channel.current?.postMessage('changed')}catch{/* Persistence already succeeded; notification must not fail the save. */}}
async function run(fn:()=>Promise<void>){setSaving(true);setError('');try{await fn()}catch(e:any){setError(e.message||'保存失败，内容仍在，请重试。')}finally{setSaving(false)}}
async function saveDraft(value:string,target=date){const r={id:'diary-draft:'+target,kind:'draft',space:'diary',date:target,text:value,updated:Date.now()};await commit([r]);}
function updateDraft(value:string){setDraft(value);clearTimeout(draftTimer.current);draftTimer.current=setTimeout(()=>{saveDraft(value).catch(e=>setError(e.message))},350)}
async function switchDiaryDate(target:string){
 if(!validDiaryDay(target)){setError('请选择今天或过去的有效日期。');return}
 if(busyRef.current){setModal({type:'busy'});return}
 if(pictures.length||processingPhotos){setError('请先发送或移除当前待发送的图片，再切换日期。');return}if(switchingDate.current||saving)return;switchingDate.current=true;setSaving(true);setError('');clearTimeout(draftTimer.current);
 const outgoingDate=dateRef.current,outgoingText=draftRef.current;const incomingText=target===outgoingDate?outgoingText:(recordRef.current.find(r=>r.id==='diary-draft:'+target)?.text||'');try{await saveDraft(outgoingText,outgoingDate);document.querySelectorAll('audio').forEach(a=>a.pause());setDate(target);dateRef.current=target;setDraft(incomingText);draftRef.current=incomingText;setPromptText('');setPictures([]);setModal(null);setView('diary');setSelected('');history.pushState({},'',`#diary/${target}`);window.scrollTo(0,0)}catch(e:any){setError(e.message||'当前草稿未保存，暂未切换日期，请重试。')}finally{switchingDate.current=false;setSaving(false)}
}
async function navigate(v:string,id=''){if(busyRef.current){setModal({type:'busy'});return}if(view==='item'&&scriptFlush.current){try{await scriptFlush.current()}catch(e:any){setError(e.message);return}}clearTimeout(draftTimer.current);try{await saveDraft(draftRef.current,dateRef.current)}catch(e:any){setError(e.message);return}document.querySelectorAll('audio').forEach(a=>a.pause());setEditor(null);setSelected(id);setView(v);setError('');history.pushState({v,id},'',`#${v}${v==='diary'?'/'+dateRef.current:id?'/'+id:''}`);window.scrollTo(0,0)}
useEffect(()=>{reload();const hash=decodeURIComponent(location.hash.slice(1)).split('/');if(NAV.some(n=>n.id===hash[0])||['excerpt','topic','item','edit','interests','calendar','interview'].includes(hash[0])){setView(hash[0]);setSelected(hash[0]==='diary'?'':hash[1]||'');if(hash[0]==='diary'&&validDiaryDay(hash[1]||''))setDate(hash[1])}channel.current=new BroadcastChannel('say-it');channel.current.onmessage=()=>{reload();flash('其他页面的已保存内容已更新')};navigator.storage?.estimate().then(setEstimate);const pop=async()=>{if(busyRef.current){history.pushState(null,'',location.href);setModal({type:'busy'});return}if(modalRef.current){setModal(null);return}const [v,id]=decodeURIComponent(location.hash.slice(1)).split('/');clearTimeout(draftTimer.current);try{await saveDraft(draftRef.current,dateRef.current)}catch(e:any){setError(e.message);return}setEditor(null);setView(v||'diary');setSelected(v==='diary'?'':id||'');if(v==='diary'&&validDiaryDay(id||''))setDate(id)};window.addEventListener('popstate',pop);return()=>{channel.current?.close();window.removeEventListener('popstate',pop);clearTimeout(draftTimer.current);clearTimeout(editorTimer.current)}},[]);
useEffect(()=>{if(ready){const r=recordRef.current.find(r=>r.id==='diary-draft:'+date);setDraft(r?.text||'')}},[date,ready]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const ac=new AbortController();Promise.resolve(context.registerTool({name:'start_excerpt_creation',title:'打开新建摘录',description:'打开空白摘录编辑器。不会保存摘录或开启麦克风。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(input&&Object.keys(input).length)throw Error('此操作不接受参数');if(busyRef.current)throw Error('请先处理当前录音');openEditor();return {status:'editor_opened'}}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort()},[ready]);
async function sendText(){if(!draft.trim()||saving)return;clearTimeout(draftTimer.current);const text=draft,id=uid(),at=Date.now();await run(async()=>{await commit([{id,kind:'message',type:'text',date,text,created:at,updated:at,prompt:promptText}],['diary-draft:'+date]);if(draftRef.current===text)setDraft('');else await saveDraft(draftRef.current);setPromptText('');flash('已保存到此浏览器')})}
async function addAudio(blob:Blob,seconds:number,started:number,interrupted:boolean){const at=Date.now();await commit([{id:uid(),kind:'message',type:'audio',date,blob,seconds,started,created:started,updated:at,interrupted,prompt:promptText}]);setPromptText('');flash('录音已保存到此浏览器')}
function askDelete(r:RecordItem){let children=records.filter(x=>x.parent===r.id);if(r.kind==='topic')children=[...children,...records.filter(x=>children.some(c=>x.parent===c.id))];const del=[r.id,...children.map(x=>x.id),`excerpt-draft:${r.id}`];const desc=r.kind==='excerpt'?`这条摘录及其 ${children.filter(x=>x.kind==='practice').length} 段练习录音将删除。`:r.kind==='practice'?'只删除这次练习录音，摘录和其他练习会保留。':r.kind==='topic'?'此主题下的全部事项、准备稿和录音将删除。':r.kind==='interest'?'主题及小话题将删除，已经保存的日记会保留。':'此内容将删除，此操作无法撤销。';setConfirm({title:'确认删除？',desc,action:async()=>{const parent=records.find(x=>x.id===r.parent);await commit(parent?[{...parent,updated:Date.now()}]:[],del,[r]);if(selected===r.id)navigate(r.kind==='excerpt'?'quotes':r.kind==='item'?'topic':r.kind==='interest'?'interests':'prep',r.kind==='item'?r.parent:'');flash('已删除')}})}
function openEditor(r?:RecordItem){if(busyRef.current)return;document.querySelectorAll('audio').forEach(a=>a.pause());const existing=recordRef.current.find(x=>x.id===`excerpt-draft:${r?.id||'new'}`);const e=existing?.value||{id:r?.id||uid(),body:r?.body||'',title:r?.title||'',source:r?.source||'',link:r?.link||'',thought:r?.thought||'',tags:(r?.tags||[]).join('，'),base:r};setEditor(e);setSelected(r?.id||'');setView('edit');setNotice(existing?'已恢复未提交草稿':'');history.pushState({},'','#edit'+(r?'/'+r.id:''))}
function editField(key:string,value:string){const next={...editor,[key]:value};setEditor(next);clearTimeout(editorTimer.current);setNotice('正在保存草稿…');editorTimer.current=setTimeout(()=>{commit([{id:`excerpt-draft:${next.base?.id||'new'}`,kind:'draft',space:'excerpt',value:next,updated:Date.now()}]).then(()=>setNotice('草稿已保存在此浏览器')).catch(e=>setError(e.message))},350)}
async function saveExcerpt(practice:boolean){if(!editor?.body.trim()||saving)return;let link=editor.link.trim();if(link){try{if(!['http:','https:'].includes(new URL(link).protocol))throw Error()}catch{setError('来源链接须为有效的 http 或 https 地址，请修改或清空。');return}}if(editor.body.length>500000){setError('正文超过 50 万字符，请分成多条保存。');return}clearTimeout(editorTimer.current);await run(async()=>{const {base,...fields}=editor;const r={...fields,link,tags:[...new Set(editor.tags.split(/[,，\n]/).map((s:string)=>s.trim()).filter(Boolean))],kind:'excerpt',updated:Date.now(),created:base?.created||Date.now()};await commit([r],[`excerpt-draft:${base?.id||'new'}`],base?[base]:undefined);setEditor(null);await navigate('excerpt',r.id);setHideText(false);setMode('看原文练习');flash('摘录已保存到此浏览器');if(practice)setTimeout(()=>document.getElementById('practice-control')?.scrollIntoView({behavior:'smooth',block:'center'}),150)})}
async function savePractice(blob:Blob,seconds:number,started:number,interrupted:boolean){if(!current)throw Error('内容已不存在');const snapshot={title:current.title,body:current.body,source:current.source,link:current.link};const r={id:uid(),kind:'practice',type:'audio',parent:current.id,blob,seconds,started,interrupted,snapshot,mode,updated:Date.now()};await commit([r,{...current,updated:Date.now()}],[],[current]);flash('这次练习已新增保存')}
async function choosePhotos(files:FileList|null){if(!files||processingPhotos)return;setError('');setProcessingPhotos(true);try{for(const file of Array.from(files).slice(0,3-pictures.length)){try{const blob=await preparePhoto(file);setPictures(p=>p.length>=3?p:[...p,{id:uid(),kind:'message',type:'image',blob,updated:Date.now()}])}catch(e:any){setError(e.message||'图片处理失败，请重新选择。')}}}finally{setProcessingPhotos(false)}}
async function sendPictures(){await run(async()=>{let index=0;for(const p of pictures){await commit([{...p,date,created:Date.now()+index++,updated:Date.now(),prompt:promptText}]);setPictures(old=>old.filter(x=>x.id!==p.id))}setPromptText('');flash('图片已保存，想说说这张照片吗？')})}
async function exportAll(){if(busy){setModal({type:'busy'});return}await run(async()=>{clearTimeout(draftTimer.current);if(view==='item')await scriptFlush.current?.();if(editor){clearTimeout(editorTimer.current);await commit([{id:`excerpt-draft:${editor.base?.id||'new'}`,kind:'draft',space:'excerpt',value:editor,updated:Date.now()}])}if(draft)await saveDraft(draft);const data=await encodeBackup(await allRecords()),url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`开口日记-备份-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);flash('备份文件已生成，请确认已保存到设备')})}
async function importFile(file?:File){if(!file)return;await run(async()=>{if(file.size>250*1024*1024)throw Error('备份超过 250 MB，请使用更小的备份文件。');const parsed=await decodeBackup(JSON.parse(await file.text()));setIncoming(parsed);setReplace(false);setModal({type:'import'})})}
const Menu=({record,onEdit}:{record:RecordItem;onEdit?:()=>void})=><DropdownMenu><DropdownMenuTrigger className="icon-button" aria-label="更多操作" disabled={busy}><MoreHorizontal size={19}/></DropdownMenuTrigger><DropdownMenuContent align="end">{onEdit&&<DropdownMenuItem onClick={onEdit}><Pencil size={16}/>编辑</DropdownMenuItem>}<DropdownMenuItem onClick={()=>askDelete(record)}><Trash2 size={16}/>删除</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
const navActive=['excerpt','edit'].includes(view)?'quotes':['topic','item','interview'].includes(view)?'prep':['interests','calendar'].includes(view)?'diary':view;
const focus=['excerpt','edit','item','interview'].includes(view);
function back(){navigate(['excerpt','edit'].includes(view)?'quotes':view==='item'?'topic':'prep',view==='item'?current?.parent:'')}
const Header=({title,sub,action}:{title:string;sub:string;action?:React.ReactNode})=><header className="page-head"><div><p className="eyebrow">YOUR WORDS, YOUR SPACE</p><h1>{title}</h1><p>{sub}</p></div>{action}</header>;
return <SidebarProvider><Sidebar className="desktop-nav"><SidebarHeader><button className="brand" onClick={()=>navigate('diary')}><span className="brand-icon"><AudioLines/></span><span>开口日记<small>say it</small></span></button></SidebarHeader><SidebarContent><div className="nav-caption">给自己的一点空间</div><nav>{NAV.map(({id,title,sub,Icon})=><button aria-current={navActive===id?'page':undefined} className={'nav-item '+(navActive===id?'active':'')} key={id} onClick={()=>navigate(id)}><Icon size={21}/><span>{title}<small>{sub}</small></span></button>)}</nav></SidebarContent><SidebarFooter><button className="local-note" onClick={()=>navigate('me')}><ShieldCheck size={18}/><span>只在此刻，只属于你<small>内容保存在此设备的浏览器中</small></span></button><div className="brand-foot">say a little. keep a little.</div></SidebarFooter></Sidebar><main className={'workspace '+(focus?'focused':'')}><div className="topline"><span>日常开口 / {NAV.find(n=>n.id===navActive)?.title}</span><button onClick={()=>navigate('me')}><i/> 此浏览器保存</button></div>{error&&<div className="error global-error" role="alert">{error}<button className="icon-button" aria-label="关闭提示" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
{!ready?<div className="empty-state"><p>正在读取此浏览器的内容…</p>{error&&<button className="outline" onClick={reload}>重新读取</button>}</div>:<>
{view==='diary'&&<DiaryV2 key={date} records={records} date={date} draft={draft} onDraftChange={updateDraft} commit={commit} onBusy={setBusy} onCalendar={()=>navigate('calendar')} onToday={()=>switchDiaryDate(today())} menu={r=><Menu record={r} onEdit={r.type==='text'?()=>{setForm({text:r.text});setModal({type:'message-edit',record:r})}:undefined}/>}/>}
{view==='calendar'&&<DiaryCalendar records={records} selected={date} onSelect={switchDiaryDate} onBack={()=>navigate('diary')} disabled={saving||busy}/>}
{view==='quotes'&&<div className="content-page"><Header title="拾句" sub="留下喜欢的表达，慢慢说成自己的话" action={<button className="primary" onClick={()=>openEditor()}><Plus size={18}/>新建摘录</button>}/><div className="quote-intro diary-green"><Quote size={32}/><div><h2>遇见一句喜欢的话，就留在这里。</h2><p>可以是一句话，也可以是一整段。想练的时候，再读一遍。</p></div></div>{records.some(r=>r.id==='excerpt-draft:new')&&<button className="draft-link" onClick={()=>openEditor()}><Pencil size={17}/>继续未保存的摘录<ChevronRight size={17}/></button>}<div className="filter-row">{['全部',...new Set(excerpts.flatMap(r=>r.tags||[]))].map(tag=><button className={tag===filter?'selected':''} aria-pressed={tag===filter} key={tag} onClick={()=>setFilter(tag)}>{tag}</button>)}<span className="muted">{excerpts.length} 条摘录</span></div>{excerpts.filter(r=>filter==='全部'||r.tags.includes(filter)).length?<div className="entry-grid">{excerpts.filter(r=>filter==='全部'||r.tags.includes(filter)).map(r=><article className="entry-card" key={r.id}><div className="entry-top"><Quote size={24}/><Menu record={r} onEdit={()=>openEditor(r)}/></div><button className="entry-link" onClick={()=>{setMode('看原文练习');setHideText(false);navigate('excerpt',r.id)}}>{r.title&&<h2>{r.title}</h2>}<p className="excerpt-preview">{r.body}</p>{r.source&&<small>— {r.source}</small>}<div className="tags">{r.tags.map((t:string)=><span key={t}>{t}</span>)}</div><footer><span>{records.filter(x=>x.kind==='practice'&&x.parent===r.id).length||'还没有'}{records.some(x=>x.kind==='practice'&&x.parent===r.id)?' 段练习':'练习记录'}</span><span>{timeLabel(r.updated)} <ArrowUpRight size={16}/></span></footer></button></article>)}</div>:<div className="empty-state"><span className="empty-icon"><Quote size={30}/></span><h2>{filter==='全部'?'留下一句想记住的话':'这个标签下还没有摘录'}</h2><p>{filter==='全部'?'也可以是一整段。你的第一条摘录，从这里开始。':'试试查看其他摘录。'}</p><button className="primary" onClick={()=>filter==='全部'?openEditor():setFilter('全部')}>{filter==='全部'?'新建摘录':'查看全部'}<Plus size={18}/></button></div>}</div>}
{view==='edit'&&<div className="editor-page"><div className="detail-header"><button className="outline" onClick={()=>setModal({type:'leave-editor'})}><ArrowLeft size={18}/>返回拾句</button><span>新建 / 编辑摘录</span></div>{!editor?<div className="empty-state"><p>继续编辑已保存的草稿，或新建一条摘录。</p><button className="primary" onClick={()=>openEditor(records.find(r=>r.id===selected))}>打开编辑器</button></div>:<><h1>{editor.base?'编辑摘录':'新建摘录'}</h1><p className="muted">把想留下的表达，放在这里。</p><div className="form-panel"><label>正文 <span className="required">必填</span><textarea className="excerpt-input" readOnly={saving} value={editor.body} onChange={e=>editField('body',e.target.value)} placeholder="输入或粘贴想留下、想练习的句子或段落。"/></label><label>标题 <small>选填</small><input readOnly={saving} value={editor.title} onChange={e=>editField('title',e.target.value)} placeholder="给这段表达起个名字"/></label><details><summary>补充信息 <span>出处、链接、我的想法和标签</span></summary><label>出处<input readOnly={saving} value={editor.source} onChange={e=>editField('source',e.target.value)} placeholder="作者、作品、演讲者或节目"/></label><label>来源链接<input readOnly={saving} value={editor.link} onChange={e=>editField('link',e.target.value)} placeholder="https://" type="url"/></label><label>我的想法<textarea readOnly={saving} value={editor.thought} onChange={e=>editField('thought',e.target.value)} placeholder="为什么喜欢？想练习哪里？"/></label><label>标签<input readOnly={saving} value={editor.tags} onChange={e=>editField('tags',e.target.value)} placeholder="多个标签用逗号分隔"/></label></details></div><div className="editor-actions"><span className="muted">{saving?'正在保存摘录…':'保存后，随时可以开始练习'}</span><div className="actions"><button className="outline" disabled={!editor.body.trim()||saving} onClick={()=>saveExcerpt(false)}>仅保存</button><button className="primary" disabled={!editor.body.trim()||saving} onClick={()=>saveExcerpt(true)}>保存并练习<ArrowUpRight size={18}/></button></div></div></>}</div>}
{view==='excerpt'&&current&&<div className="content-page"><div className="detail-header"><button className="outline" onClick={back}><ArrowLeft size={18}/>拾句</button><div className="actions"><button disabled={busy} className="outline" onClick={()=>openEditor(current)}><Pencil size={16}/>编辑摘录</button><Menu record={current}/></div></div><h1>{current.title||'留给自己的表达'}</h1><div className="metadata">{current.source&&<span>{current.source}</span>}{current.link&&<a href={current.link} target="_blank" rel="noreferrer">查看来源 ↗</a>}<div className="tags">{current.tags?.map((t:string)=><span key={t}>{t}</span>)}</div></div><div className="practice-layout"><section className="reading-panel"><div className="section-title"><h2>原文</h2><button className="subtle" onClick={()=>setHideText(!hideText)}>{hideText?<Eye size={16}/>:<EyeOff size={16}/>} {hideText?'查看原文':'收起原文'}</button></div>{hideText?<div className="hidden-text"><EyeOff size={30}/><p>原文已收起</p><small>试着用自己的话说一遍，随时可以展开。</small></div>:<p className="full-text">{current.body}</p>}{current.thought&&<div className="thought"><h2>我的想法</h2><p>{current.thought}</p></div>}</section><aside className="practice-side"><div id="practice-control" className="practice-control"><Tabs value={mode} onValueChange={v=>{if(!busy){setMode(String(v));setHideText(v==='收起原文复述')}}}><TabsList className="mode-tabs"><TabsTrigger value="看原文练习" disabled={busy}>看原文练习</TabsTrigger><TabsTrigger value="收起原文复述" disabled={busy}>收起原文复述</TabsTrigger></TabsList></Tabs><Recorder key={current.id} label={practices.length?'再练一遍（新增）':'开始练习'} onSave={savePractice} onBusy={setBusy} note="每段最长 5 分钟 · 保留之前的练习"/></div><div className="section-title"><h2>练习记录</h2><small>{practices.length} 段</small></div>{practices.length?practices.map(p=><div className="audio-card" key={p.id}><div className="section-title"><span>{timeLabel(p.started)}</span><Menu record={p}/></div><small>{p.mode} · {fmt(p.seconds)}{p.interrupted?' · 中断片段':''}</small>{!busy&&<Media record={p}/>}<button className="subtle" onClick={()=>setModal({type:'snapshot',record:p})}>本次练习原文 <ChevronRight size={14}/></button></div>):<div className="practice-empty"><AudioLines size={28}/><p>读一遍，或用自己的话说一遍。<br/>想练的时候再开始。</p></div>}</aside></div></div>}
{view==='prep'&&<div className="content-page"><Header title="场景准备" sub="先整理问题和准备稿，再做一次限时模拟。" action={<button className="primary" onClick={()=>{setForm({name:''});setModal({type:'topic-new'})}}><Plus size={18}/>新建主题</button>}/><div className="quote-intro lavender"><FolderHeart size={32}/><div><h2>先准备，再进入真实节奏。</h2><p>进入主题后，可开启逐题限时模拟：隐藏稿件、回答、保存、回听。</p></div></div>{topics.length?<div className="entry-grid">{topics.map(t=><article className="entry-card" key={t.id}><div className="entry-top"><FolderHeart size={24}/><Menu record={t} onEdit={()=>{setForm({name:t.name});setModal({type:'rename',record:t})}}/></div><button className="entry-link" onClick={()=>navigate('topic',t.id)}><h2>{t.name}</h2><p className="muted">{records.filter(r=>r.kind==='item'&&r.parent===t.id).length} 个表达事项</p><footer><span>{timeLabel(t.updated)}</span><ArrowUpRight size={18}/></footer></button></article>)}</div>:<div className="empty-state"><span className="empty-icon lavender"><FolderHeart size={30}/></span><h2>下一次，你想为哪句话做准备？</h2><p>实习面试、课程展示，或是一次认真沟通。<br/>先给它起个名字，慢慢整理就好。</p><button className="primary" onClick={()=>{setForm({name:''});setModal({type:'topic-new'})}}>新建主题<Plus size={18}/></button></div>}</div>}
{view==='topic'&&current&&<div className="content-page"><div className="detail-header"><button className="outline" onClick={()=>navigate('prep')}><ArrowLeft size={18}/>场景准备</button><Menu record={current} onEdit={()=>{setForm({name:current.name});setModal({type:'rename',record:current})}}/></div><Header title={current.name} sub="把问题、提纲和试说，放在一起。" action={<button className="primary" onClick={()=>{setForm({name:''});setModal({type:'item-new'})}}><Plus size={18}/>添加事项</button>}/><section className="interview-launch lavender"><div><h2>限时模拟面试</h2><p>逐题回答 · 不看稿 · 每题 2 分钟 · 成功保存后进入下一题</p><small>使用本主题的已有问题，无 AI 调用费用。</small></div><button className="primary" disabled={!records.some(r=>r.kind==='item'&&r.parent===current.id)} onClick={()=>navigate('interview',current.id)}>开始模拟</button></section>{records.filter(r=>r.kind==='item'&&r.parent===current.id).map(r=><div className="list-row" key={r.id}><button onClick={()=>navigate('item',r.id)}><h2>{r.name}</h2><p>{r.script?'已有准备稿':'还没有准备稿'} · {r.blob?'已有录音':'还没有录音'}</p></button><Menu record={r} onEdit={()=>{setForm({name:r.name});setModal({type:'rename',record:r})}}/><ChevronRight size={18}/></div>)}{!records.some(r=>r.kind==='item'&&r.parent===current.id)&&<div className="empty-state"><h2>想回答的问题，或想表达的事</h2><p>用短语记下来就可以，不需要完整的题目。</p></div>}</div>}
{view==='interview'&&current&&<Interview key={current.id} topic={current} items={records.filter(r=>r.kind==='item'&&r.parent===current.id).sort((a,b)=>a.created-b.created)} onBusy={setBusy} onBack={()=>navigate('topic',current.id)} onSave={async(item,blob,seconds,started,interrupted)=>{await commit([{...item,blob,type:'audio',seconds,started,interrupted,interviewPrompt:item.name,updated:Date.now()}],[],[item]);flash('本题回答已保存')}}/>}
{view==='item'&&current&&<div className="content-page"><div className="detail-header"><button className="outline" onClick={back}><ArrowLeft size={18}/>返回主题</button><Menu record={current}/></div><h1>{current.name}</h1><div className="practice-layout"><section className="reading-panel"><ScriptEditor key={current.id} record={current} readOnly={busy} onSaved={reload} flushRef={scriptFlush}/></section><aside className="practice-side"><div className="practice-control"><Recorder key={current.id} beforeStart={async()=>{await scriptFlush.current?.()}} label={current.blob?'重新录音（替换）':'开始录音'} note="每段最长 5 分钟 · 成功保存后替换当前录音" onBusy={setBusy} onSave={async(blob,seconds,started,interrupted)=>{await commit([{...current,blob,type:'audio',seconds,started,interrupted,updated:Date.now()}],[],[current]);flash('最新录音已保存')}}/></div><h2>当前已保存的录音</h2>{current.blob?<div className="audio-card"><small>{timeLabel(current.started)} · {fmt(current.seconds)}</small>{!busy&&<Media record={current}/>}<button className="subtle danger" disabled={busy} onClick={()=>setConfirm({title:'删除当前录音？',desc:'准备事项和准备稿会保留。',action:async()=>{const {blob,type,seconds,started,...rest}=current;await commit([{...rest,updated:Date.now()}],[],[current])}})}>删除录音</button></div>:<div className="practice-empty"><Mic size={28}/><p>先整理想法，再说一遍。<br/>准备稿留空也没关系。</p></div>}</aside></div></div>}
{view==='interests'&&<div className="content-page"><div className="detail-header"><button className="outline" onClick={()=>navigate('diary')}><ArrowLeft size={18}/>返回日记</button></div><Header title="聊聊你喜欢的" sub="从熟悉的兴趣开始，表达可以更轻松一点。" action={<button className="primary" onClick={()=>{setForm({name:''});setModal({type:'interest-new'})}}><Plus size={18}/>新建主题</button>}/>{interests.map(r=><article className="entry-card interest-card" key={r.id}><div className="section-title"><h2><Leaf size={20}/>{r.name}</h2><Menu record={r} onEdit={()=>{setForm({name:r.name});setModal({type:'rename',record:r})}}/></div><div className="topic-chips">{(r.prompts||[]).map((p:string,i:number)=><div key={i}><button onClick={()=>{setPromptText(`${r.name} · ${p}`);navigate('diary')}}>{p}</button><button aria-label="编辑小话题" className="icon-button" onClick={()=>{setForm({name:p});setModal({type:'prompt-edit',record:r,index:i})}}><Pencil size={14}/></button><button aria-label="删除小话题" className="icon-button" onClick={()=>setConfirm({title:'删除小话题？',desc:'已经保存的日记会保留。',action:async()=>{await commit([{...r,prompts:r.prompts.filter((_:any,j:number)=>j!==i),updated:Date.now()}],[],[r])}})}><X size={14}/></button></div>)}</div><div className="actions"><button className="primary" onClick={()=>{setPromptText(r.name);navigate('diary')}}>聊聊这个主题<ArrowUpRight size={18}/></button><button className="outline" onClick={()=>{setForm({name:''});setModal({type:'prompt-new',record:r})}}><Plus size={18}/>添加小话题</button></div></article>)}{!interests.length&&<div className="empty-state"><span className="empty-icon sage"><Leaf size={30}/></span><h2>从你喜欢的内容开始</h2><p>可以先建一个主题，不必准备问题。</p><button className="primary" onClick={()=>{setForm({name:''});setModal({type:'interest-new'})}}>新建兴趣主题</button></div>}</div>}
{view==='me'&&<div className="content-page settings-page"><Header title="我的" sub="把每一次表达，妥善收好。"/><section className="storage-card aqua"><HardDrive size={32}/><div><h2>此设备 · 此浏览器</h2><p>你的日记、摘录和录音保存在这里。<br/>清理浏览器、更换设备或域名，可能无法再访问原内容。</p><small>{estimate?.usage!=null?`本站存储估计用量 ${(estimate.usage/1024/1024).toFixed(2)} MB`:'浏览器暂未提供可靠的存储用量。'}</small></div></section><section className="settings-section"><h2>备份与恢复</h2><p>给记录多留一份。备份文件包含私人内容，请妥善保管。</p><div className="backup-grid"><button onClick={exportAll} disabled={saving}><Download/><h3>导出全部数据</h3><small>包含文字、图片、录音和草稿</small><ArrowUpRight className="arrow"/></button><button onClick={()=>importInput.current?.click()} disabled={saving}><Upload/><h3>导入备份</h3><small>先检查内容，再确认合并</small><ArrowUpRight className="arrow"/></button></div></section><section className="settings-section"><h2>我的内容</h2>{NAV.slice(0,3).map(({id,title,Icon})=><button className="management-row" key={id} onClick={()=>navigate(id)}><Icon size={20}/><span>{title}</span><small>{id==='diary'?new Set(records.filter(r=>r.kind==='message').map(r=>r.date)).size:id==='quotes'?excerpts.length:topics.length} {id==='diary'?'篇':id==='quotes'?'条':'个主题'}</small><ChevronRight size={18}/></button>)}</section><details className="privacy"><summary><ShieldCheck size={18}/>关于隐私与本地保存</summary><p>应用不主动上传日记、图片、摘录、录音或准备稿。访问时会请求必要的网站资源。使用统计记录页面访问、功能入口和录音时长等操作信息，不包含日记正文、照片、声音或准备稿，不启用页面回放。这里没有账号隔离，也不是加密保险箱；使用同一浏览器的人可能访问这些内容。主动打开来源链接时会前往外部网站。</p><p>建议定期导出备份。本地保存不等于永久备份，完整离线启动不在当前支持范围内。</p></details><button className="danger clear-button" onClick={()=>setModal({type:'clear-start'})}><Trash2 size={17}/>清除全部本地数据</button></div>}
{['excerpt','topic','item','interview'].includes(view)&&!current&&<div className="empty-state"><h2>这条内容已不存在</h2><p>可能已被删除，或不在此浏览器中。</p><button className="primary" onClick={()=>navigate(view==='excerpt'?'quotes':'prep')}>返回列表</button></div>}
</>}
<input ref={photoInput} hidden type="file" multiple accept="image/*" onChange={e=>{choosePhotos(e.target.files);e.target.value=''}}/><input ref={importInput} hidden type="file" accept=".json,application/json" onChange={e=>{importFile(e.target.files?.[0]);e.target.value=''}}/>
</main>{!focus&&<nav className="mobile-nav" aria-label="主导航">{NAV.map(({id,title,Icon})=><button className={navActive===id?'active':''} aria-current={navActive===id?'page':undefined} key={id} onClick={()=>navigate(id)}><Icon size={21}/>{title}</button>)}</nav>}
<Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className="app-dialog"><DialogTitle>{({history:'历史日记',snapshot:'本次练习原文',busy:'请先处理当前录音','leave-editor':'离开编辑？','clear-start':'清除全部本地数据','clear-final':'最后确认',import:'检查备份内容','message-edit':'编辑这条日记'} as any)[modal?.type]||'留一个新的话题'}</DialogTitle><DialogDescription>{modal?.type==='busy'?'请先结束录音、完成保存，或发送／移除待发送的图片，再离开当前页面。':modal?.type==='snapshot'?'以下是这次录音开始时保留的原文。':'内容只保存在此设备的浏览器中。'}</DialogDescription>
{error&&<p className="error" role="alert">{error}</p>}
{modal?.type==='snapshot'&&<div className="snapshot">{modal.record.snapshot.body!==current?.body&&<p className="notice-panel">这次练习使用的是修改前的原文。</p>}<h2>{modal.record.snapshot.title}</h2><p className="full-text">{modal.record.snapshot.body}</p><small>{modal.record.snapshot.source}</small></div>}
{modal?.type==='leave-editor'&&<div className="stack-actions"><button className="primary" onClick={()=>setModal(null)}>继续编辑</button><button className="outline" onClick={()=>run(async()=>{clearTimeout(editorTimer.current);if(editor)await commit([{id:`excerpt-draft:${editor.base?.id||'new'}`,kind:'draft',space:'excerpt',value:editor,updated:Date.now()}]);setModal(null);navigate('quotes')})}>保留草稿后离开</button><button className="subtle danger" onClick={()=>run(async()=>{clearTimeout(editorTimer.current);await commit([],[`excerpt-draft:${editor?.base?.id||'new'}`]);setModal(null);navigate('quotes')})}>放弃修改</button></div>}
{modal?.type==='clear-start'&&<><p>将清除所有日记、图片、录音、摘录、练习原文、准备稿、兴趣主题和草稿。已导出的外部文件不受影响。</p><div className="actions"><button className="primary" onClick={exportAll}>先导出备份</button><button className="outline danger" onClick={()=>{setForm({name:''});setModal({type:'clear-final'})}}>继续清除</button></div></>}
{modal?.type==='clear-final'&&<><label>请输入“清除”以确认<input value={form.name||''} onChange={e=>setForm({name:e.target.value})}/></label><button className="primary danger-bg" disabled={form.name!=='清除'||saving} onClick={()=>run(async()=>{await wipe();setRecords([]);setDraft('');setEditor(null);setModal(null);channel.current?.postMessage('changed');flash('本地数据已清除')})}>确认清除</button></>}
{modal?.type==='import'&&incoming&&<><p>备份包含 {incoming.filter(r=>r.kind==='message').length} 条日记消息、{incoming.filter(r=>r.kind==='excerpt').length} 条摘录、{incoming.filter(r=>r.kind==='practice').length} 段练习和 {incoming.filter(r=>r.kind==='topic').length} 个准备主题。</p><p className="notice-panel">{incoming.filter(r=>records.some(x=>x.id===r.id)).length} 条记录具有相同标识。默认保留此浏览器内容。</p><label className="check-label"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>冲突时采用备份内容（包含对应正文、录音及原文快照）</label><button className="primary" disabled={saving} onClick={()=>run(async()=>{const add=incoming.filter(r=>replace||!records.some(x=>x.id===r.id));await commit(add);flash(`导入完成：新增 ${add.filter(r=>!records.some(x=>x.id===r.id)).length}，更新 ${add.filter(r=>records.some(x=>x.id===r.id)).length}，跳过 ${incoming.length-add.length}`);setIncoming(null);setModal(null)})}>确认合并</button></>}
{modal?.type==='message-edit'&&<><label>日记正文<textarea value={form.text||''} onChange={e=>setForm({text:e.target.value})}/></label><button className="primary" disabled={!form.text?.trim()||saving} onClick={()=>run(async()=>{await commit([{...modal.record,text:form.text,updated:Date.now()}],[],[modal.record]);setModal(null);flash('修改已保存')})}>保存修改</button></>}
{['topic-new','item-new','interest-new','rename','prompt-new','prompt-edit'].includes(modal?.type)&&<><label>{modal?.type.startsWith('prompt')?'小话题':modal?.type==='item-new'?'问题或想表达的事':'名称'}<input value={form.name||''} onChange={e=>setForm({name:e.target.value})} placeholder="用你自己的话，给它起个名字" autoFocus/></label>{modal?.type==='interest-new'&&<div className="topic-chips">{['电影','音乐','美食','运动','游戏','阅读'].map(t=><button className="outline" key={t} onClick={()=>setForm({name:t})}>{t}</button>)}</div>}<button className="primary" disabled={!form.name?.trim()||saving} onClick={()=>run(async()=>{const name=form.name.trim(),at=Date.now();if(modal.type==='rename')await commit([{...modal.record,name,updated:at}],[],[modal.record]);else if(modal.type.startsWith('prompt')){const prompts=[...(modal.record.prompts||[])];if(modal.type==='prompt-edit')prompts[modal.index]=name;else prompts.push(name);await commit([{...modal.record,prompts,updated:at}],[],[modal.record])}else {const kind=modal.type==='topic-new'?'topic':modal.type==='item-new'?'item':'interest';const r={id:uid(),kind,name,updated:at,created:at,...(kind==='item'?{parent:current!.id,script:''}:{}),...(kind==='interest'?{prompts:[]}: {})};await commit([r,...(kind==='item'?[{...current!,updated:at}]:[])],[],kind==='item'?[current!]:undefined)}setModal(null);flash('已保存到此浏览器')})}>保存</button></>}
</DialogContent></Dialog>
<AlertDialog open={!!confirm} onOpenChange={open=>{if(!open)setConfirm(null)}}><AlertDialogContent className="app-dialog"><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.desc}</AlertDialogDescription><div className="actions"><button className="outline" onClick={()=>setConfirm(null)}>取消</button><button className="primary danger-bg" disabled={saving} onClick={()=>run(async()=>{await confirm.action();setConfirm(null)})}>确认删除</button></div></AlertDialogContent></AlertDialog>
</SidebarProvider>}
