'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,X,RotateCcw,Play,Pause} from 'lucide-react';
import type {RecordItem} from '@/lib/store';
export function Recorder({limit=300,label='开始练习',note='每段最长 5 分钟 · 新增保存',onSave,onBusy,beforeStart}:{limit?:number;label?:string;note?:string;onSave:(blob:Blob,seconds:number,start:number,interrupted:boolean)=>Promise<void>;onBusy?:(busy:boolean)=>void;beforeStart?:()=>Promise<void>}){
 const [status,setStatus]=useState('idle'),[seconds,setSeconds]=useState(0),[error,setError]=useState(''),[pending,setPending]=useState<any>(null),[hold,setHold]=useState(false),[cancelGesture,setCancelGesture]=useState(false);
 const rec=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),cancelled=useRef(false),startTime=useRef(0),timer=useRef<any>(null),busy=useRef(false),holdActive=useRef(false),initialY=useRef(0),interrupted=useRef(false),saveCallback=useRef(onSave);saveCallback.current=onSave;
 const cleanup=()=>{clearInterval(timer.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null};
 const end=(cancel=false)=>{cancelled.current=cancel;if(rec.current?.state==='recording')rec.current.stop();else if(cancel){cleanup();setStatus('idle');busy.current=false;onBusy?.(false)}};
 async function persist(p:any){setPending(p);setStatus('saving');try{await p.save(p.blob,p.seconds,p.start,p.interrupted);setPending(null);setStatus('idle');setError('');busy.current=false;onBusy?.(false)}catch(e:any){setError(e.message||'录音尚未保存，请重试。');setPending(p);setStatus('failed')}}
 async function start(isHold=false){if(busy.current)return;busy.current=true;onBusy?.(true);setError('');setStatus('permission');cancelled.current=false;interrupted.current=false;document.querySelectorAll('audio').forEach(a=>a.pause());(document.activeElement as HTMLElement)?.blur();try{await beforeStart?.();if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('此浏览器不支持录音，请使用 Safari 或 Chrome 系统浏览器。');const media=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=media;if(cancelled.current||(isHold&&!holdActive.current)){cleanup();setStatus('idle');busy.current=false;onBusy?.(false);setError('麦克风已允许，请再次按住说话。');return}const mr=new MediaRecorder(media),parts:BlobPart[]=[];rec.current=mr;const save=saveCallback.current;mr.ondataavailable=e=>{if(e.data.size)parts.push(e.data)};mr.onstop=()=>{const length=Math.min(limit,Math.round((Date.now()-startTime.current)/1000));cleanup();if(cancelled.current){setStatus('idle');busy.current=false;onBusy?.(false);return}const blob=new Blob(parts,{type:mr.mimeType});if(!blob.size){setStatus('idle');setError('没有取得有效音频，请重新录制。');busy.current=false;onBusy?.(false);return}void persist({blob,seconds:length,start:startTime.current,interrupted:interrupted.current,save})};mr.onerror=()=>{interrupted.current=true;end()};media.getTracks().forEach(t=>t.onended=()=>{if(mr.state==='recording'){interrupted.current=true;end()}});startTime.current=Date.now();mr.start(250);setSeconds(0);setStatus('recording');timer.current=setInterval(()=>{const s=Math.floor((Date.now()-startTime.current)/1000);setSeconds(Math.min(s,limit));if(s>=limit)end()},200)}catch(e:any){cleanup();setStatus('idle');busy.current=false;onBusy?.(false);setError(e.name==='NotAllowedError'?'麦克风权限未开启。请在浏览器网站设置中允许麦克风后重试，已有内容仍然保留。':e.message||'录音失败，请重试。')}}
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(busy.current){e.preventDefault();e.returnValue=''}};const hidden=()=>{if(document.hidden&&rec.current?.state==='recording'){interrupted.current=true;end()}};window.addEventListener('beforeunload',leave);document.addEventListener('visibilitychange',hidden);return()=>{cancelled.current=true;if(rec.current?.state==='recording')rec.current.stop();cleanup();window.removeEventListener('beforeunload',leave);document.removeEventListener('visibilitychange',hidden)}},[]);
 return <div className={'recorder '+(status==='recording'?'recording':'')}><div aria-live="polite">{status==='permission'&&<p>正在请求麦克风权限…</p>}{status==='saving'&&<><p>正在保存这次录音…</p><small>录音已结束，正在写入此浏览器。</small></>}{status==='recording'&&<><p className="timer"><i/>{fmt(seconds)} <span>/ {fmt(limit)}</span></p><p>{cancelGesture?'松手取消':limit-seconds<=10?`还剩 ${limit-seconds} 秒`:'正在录音，慢慢说就好'}</p></>}</div>{(status==='idle'||(hold&&(status==='recording'||status==='permission')))&&(hold?<button className="primary record-main" style={{touchAction:'none'}} onPointerDown={e=>{if(e.button!==0||busy.current)return;e.currentTarget.setPointerCapture(e.pointerId);holdActive.current=true;initialY.current=e.clientY;setCancelGesture(false);void start(true)}} onPointerMove={e=>{if(holdActive.current){cancelled.current=initialY.current-e.clientY>64;setCancelGesture(cancelled.current)}}} onPointerUp={()=>{holdActive.current=false;end(cancelled.current)}} onPointerCancel={()=>{holdActive.current=false;end(true)}}><Mic size={20}/>{status==='recording'?(cancelGesture?'松手取消':'松手保存'):'按住说话'}</button>:<button className="primary record-main" onClick={()=>start()}><Mic size={20}/>{label}</button>)}{status==='recording'&&<div className="actions"><button className="primary" onClick={()=>end()}><Square size={16}/>结束并保存</button><button className="secondary" onClick={()=>end(true)}><X size={16}/>取消</button></div>}{status==='permission'&&<button className="secondary" onClick={()=>{cancelled.current=true}}>取消请求</button>}{(status==='failed'||(status==='saving'&&pending))&&<div className="actions">{status==='failed'&&<button className="primary" onClick={()=>persist(pending)}><RotateCcw size={16}/>重试保存</button>}<button className="outline" onClick={()=>{const url=URL.createObjectURL(pending.blob);const a=document.createElement('a');a.href=url;a.download='未保存录音.'+(pending.blob.type.includes('mp4')?'m4a':'webm');a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}}>下载这段录音</button>{status==='failed'&&<button className="secondary" onClick={()=>{setPending(null);setStatus('idle');setError('');busy.current=false;onBusy?.(false)}}>放弃这次录音</button>}</div>}<small>{hold?'松手保存，上滑取消 · 最长 60 秒':note}</small>{limit===60&&status==='idle'&&<button className="subtle" onClick={()=>setHold(!hold)}>{hold?'改用点击录音':'改用按住说话'}</button>}{error&&<p className="error" role="alert">{error}</p>}</div>
}
export function fmt(s:number){return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`}
export function Media({record}:{record:RecordItem}){
 const [url,setUrl]=useState(''),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[duration,setDuration]=useState(record.seconds||0);const audio=useRef<HTMLAudioElement>(null);
 useEffect(()=>{setError('');setPosition(0);setPlaying(false);setDuration(record.seconds||0);if(!(record.blob instanceof Blob))return;const u=URL.createObjectURL(record.blob);setUrl(u);return()=>{audio.current?.pause();URL.revokeObjectURL(u)}},[record.blob,record.seconds]);
 async function toggle(){const player=audio.current;if(!player)return;setError('');if(!player.paused){player.pause();return}document.querySelectorAll('audio').forEach(a=>{if(a!==player)a.pause()});try{await player.play()}catch{setError('暂时无法播放，请再试一次；录音仍保留，可导出备份。')}}
 return <>{record.type==='image'?<a href={url} target="_blank" rel="noreferrer"><img src={url} alt="日记照片，点击查看完整图片" className="diary-image"/></a>:<div className="voice-bubble"><audio ref={audio} hidden playsInline style={{display:'none'}} src={url} preload="metadata" onLoadedMetadata={e=>{if(Number.isFinite(e.currentTarget.duration))setDuration(e.currentTarget.duration)}} onDurationChange={e=>{if(Number.isFinite(e.currentTarget.duration))setDuration(e.currentTarget.duration)}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={e=>setPosition(e.currentTarget.currentTime)} onError={()=>setError('回听失败，音频仍保留。建议先导出备份。')}/><button className="voice-play" aria-label={playing?'暂停录音':'播放录音'} disabled={!url} onClick={toggle}>{playing?<Pause size={20}/>:<Play size={20}/>}</button><div className="voice-track"><div className="voice-track-label"><span>{playing?'正在播放':'语音记录'}</span><time>{fmt(Math.floor(position))} / {fmt(Math.round(duration))}</time></div><input aria-label="录音播放进度" type="range" min="0" max={duration||1} step="0.1" value={Math.min(position,duration||1)} disabled={!duration} onChange={e=>{const target=Number(e.target.value);if(audio.current){try{audio.current.currentTime=target;setPosition(target)}catch{setError('这段录音暂不支持跳转播放。')}}}}/></div></div>}{error&&<p className="error" role="alert">{error}</p>}</>
}
