export type RecordItem = {id:string; kind:string; updated:number; [key:string]:any};
const STORAGE_TIMEOUT = 15000;
let connection:Promise<IDBDatabase>|undefined;
function timed<T>(work:Promise<T>,message:string):Promise<T>{return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(message)),STORAGE_TIMEOUT);work.then(v=>{clearTimeout(timer);resolve(v)},e=>{clearTimeout(timer);reject(e)})})}
export function database(){if(connection)return connection;connection=new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('say-it-v2',1);let expired=false;const timer=setTimeout(()=>{expired=true;connection=undefined;reject(new Error('浏览器存储响应超时，请重试。未保存录音仍然保留。'))},STORAGE_TIMEOUT);r.onupgradeneeded=()=>r.result.createObjectStore('records',{keyPath:'id'});r.onsuccess=()=>{clearTimeout(timer);if(expired){r.result.close();return}const db=r.result;db.onversionchange=()=>{db.close();connection=undefined};db.onclose=()=>{connection=undefined};resolve(db)};r.onerror=()=>{clearTimeout(timer);connection=undefined;reject(r.error)};r.onblocked=()=>{clearTimeout(timer);expired=true;connection=undefined;reject(new Error('浏览器存储被其他页面占用，请关闭其他开口日记页面后重试。'))}});return connection}
// Serialize media before opening a transaction. ArrayBuffer avoids browser-specific
// structured-cloning of MediaRecorder's composite Blob and keeps the transaction short.
export async function toStoredRecord(record:RecordItem):Promise<RecordItem>{if(!(record.blob instanceof Blob))return record;const {blob,...rest}=record;const mediaBytes=await timed(blob.arrayBuffer(),'音频整理超时，录音仍然保留，可下载或重试保存。');return {...rest,mediaBytes,mediaType:blob.type}}
export function fromStoredRecord(record:RecordItem):RecordItem{if(!(record.mediaBytes instanceof ArrayBuffer))return record;const {mediaBytes,mediaType,...rest}=record;return {...rest,blob:new Blob([mediaBytes],{type:mediaType||'application/octet-stream'})}}
export async function allRecords():Promise<RecordItem[]>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('records'),r=tx.objectStore('records').getAll();const timer=setTimeout(()=>{try{tx.abort()}catch{}reject(new Error('读取浏览器存储超时，请重试。'))},STORAGE_TIMEOUT);r.onsuccess=()=>{clearTimeout(timer);resolve(r.result.map(fromStoredRecord))};r.onerror=()=>{clearTimeout(timer);reject(r.error)};tx.onabort=()=>{clearTimeout(timer);reject(tx.error||new Error('读取已中断，请重试。'))}})}
export async function writeRecords(records:RecordItem[],removed:string[]=[],expected?:RecordItem[]){const stored=await Promise.all(records.map(toStoredRecord));const db=await database();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('records','readwrite'),s=tx.objectStore('records');let reason:Error|null=null;const timer=setTimeout(()=>{reason=new Error('浏览器保存响应超时。录音仍然保留，可重试或先下载这段录音。');try{tx.abort()}catch{}reject(reason)},STORAGE_TIMEOUT);const fail=(e:unknown)=>{reason=e instanceof Error?e:new Error('保存失败，请重试。');try{tx.abort()}catch{}clearTimeout(timer);reject(reason)};tx.oncomplete=()=>{clearTimeout(timer);resolve()};tx.onerror=()=>{clearTimeout(timer);reject(reason||tx.error||new Error('保存失败，请重试。'))};tx.onabort=()=>{clearTimeout(timer);reject(reason||tx.error||new Error('保存已中断，请重试。'))};const perform=()=>{try{removed.forEach(id=>s.delete(id));stored.forEach(r=>s.put(r))}catch(e){fail(e)}};if(expected?.length){let left=expected.length;expected.forEach(e=>{const r=s.get(e.id);r.onsuccess=()=>{if(!r.result||r.result.updated!==e.updated){fail(new Error('内容已在其他页面修改或删除。当前输入和未保存录音仍然保留。'));return}if(--left===0)perform()};r.onerror=()=>fail(r.error)})}else perform()})}
export async function wipe(){const db=await database();return new Promise<void>((resolve,reject)=>{const t=db.transaction('records','readwrite');const timer=setTimeout(()=>{try{t.abort()}catch{}reject(new Error('清除未完成，请重试。'))},STORAGE_TIMEOUT);t.oncomplete=()=>{clearTimeout(timer);resolve()};t.onerror=t.onabort=()=>{clearTimeout(timer);reject(t.error||new Error('清除未完成'))};t.objectStore('records').clear()})}
export const uid=()=>crypto.randomUUID();
export async function encodeBackup(records:RecordItem[]){return {format:'say-it',version:2,records:await Promise.all(records.map(async r=>{if(!(r.blob instanceof Blob))return r;const data=await new Promise<string>((ok,no)=>{const f=new FileReader();f.onload=()=>ok(String(f.result));f.onerror=no;f.readAsDataURL(r.blob)});return {...r,blob:undefined,media:data}}))}}
export async function decodeBackup(raw:any):Promise<RecordItem[]>{if(raw?.format!=='say-it'||![1,2].includes(raw.version)||!Array.isArray(raw.records))throw Error('无法识别的备份格式或版本。现有数据未改变。');const ids=new Set();const records=await Promise.all(raw.records.map(async(r:any)=>{if(!r||typeof r.id!=='string'||ids.has(r.id)||!['message','excerpt','practice','topic','item','interest','draft'].includes(r.kind)||!Number.isFinite(r.updated))throw Error('备份包含无效或重复的记录');ids.add(r.id);if(r.kind==='excerpt'&&typeof r.body!=='string')throw Error('摘录正文损坏');if(r.link&&!/^https?:\/\//.test(r.link))throw Error('备份包含无效来源链接');if(r.media){if(typeof r.media!=='string'||!/^data:(audio|image)\/[\w.+-]+(?:;[^,]*)?;base64,/.test(r.media))throw Error('备份媒体损坏');const [,type,b64]=r.media.match(/^data:([^;,]+).*?;base64,(.+)$/)||[];if(!b64)throw Error('备份媒体为空');const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));if(!bytes.length)throw Error('备份媒体为空');const {media,...rest}=r;return {...rest,blob:new Blob([bytes],{type})}}if(['audio','image'].includes(r.type)||r.kind==='practice')throw Error('备份缺少媒体文件');return r}));for(const r of records){if(r.parent&&!ids.has(r.parent))throw Error('备份存在缺失的关联内容');if(r.kind==='practice'&&!r.snapshot)throw Error('练习原文快照缺失')}return records}
